// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./src/jquery"
import "./controllers"
import "./src/js/main"
import "./src/js/ajax-contact"
import "./src/js/jquery.countdown.min"
import "./src/js/jquery.counterup.min"
import "./src/js/jquery.magnific-popup.min"
import "./src/js/jquery.nice-select.min"
import "./src/js/jquery.nice-number.min"
import "./src/js/map-script"
import "./src/js/slick.min"
import "./src/js/validator.min"
import "./src/js/jquery.waypoints.min"
import * as bootstrap from "bootstrap"
global.toastr = require("toastr")